# backend-proxy-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-nginx-proxy
  namespace: bookstore-platform

  nginx.conf: |
    events {}
    http {
      server {
        listen 3000;
        location / {
          proxy_pass http://127.0.0.1:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
